# Generated by Django 4.0.4 on 2022-05-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_remove_listitem_setted_done_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='setted_done_by',
        ),
        migrations.AddField(
            model_name='listitem',
            name='setted_done_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
