# Generated by Django 4.0.4 on 2022-05-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributors', models.ManyToManyField(null=True, related_name='contributors', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='list.list')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('setted_done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checker', to='accounts.account')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='list_items',
            field=models.ManyToManyField(related_name='items', to='list.listitem'),
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
