# Generated by Django 4.0.4 on 2022-05-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('list', '0002_rename_added_by_listitem_added_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='setted_done_by',
        ),
        migrations.AddField(
            model_name='listitem',
            name='setted_done_by',
            field=models.ManyToManyField(null=True, related_name='checker', to='accounts.account'),
        ),
    ]
