# Generated by Django 4.0.4 on 2022-05-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_remove_listitem_setted_done_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
